# docker-compose.yml
version: '3.8'

services:
  # PostgreSQL Database Service
  postgres-db:
    image: postgres:15-alpine
    container_name: codeyarn-postgres-db
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: codeyarn_user
      POSTGRES_PASSWORD: codeyarn_password
      POSTGRES_DB: codeyarn_db
    volumes:
      - postgres-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: unless-stopped

# Define named volume for data persistence
volumes:
  postgres-data:
    driver: local
